#define WINDOW_WIDTH  1200
#define WINDOW_HEIGHT 800
#define GAME_FPS 60

#define PLAYER_WIDTH  120
#define PLAYER_HEIGHT 96

#define RANKING_QUANTITY 5
#define RANKING_NAME_LENGTH 16

#define OBSTACLE_WIDTH  200
#define OBSTACLE_HEIGHT 800
#define OBSTACLE_QUANTITY (WINDOW_WIDTH / OBSTACLE_WIDTH) + 1